engine = inform7
title = Babel Fish Puzzle from HHGG
author = An Homage To Adams and Meretzky
description = A recreation of the classic Babel Fish puzzle from The Hitchhiker's Guide to the Galaxy text adventure. Place items in the right spots, then push the button to catch the fish.
binary = babel.ulx
source = story.ni
walkthrough = walkthrough.txt
tags = classic, puzzle
sourceLabel = babel.ni
hub = yes
