engine = inform7
title = Babel Fish Puzzle - 2013
author = An Homage To Adams and Meretzky
description = A recreation of the classic Babel Fish puzzle from The Hitchhiker's Guide to the Galaxy text adventure.
binary = babel.ulx
source = story.ni
walkthrough = walkthrough.txt
tags = classic, puzzle
